application.project.security.provider.admin:
    resource: '@ApplicationProjectSecurityAdminBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.project.security.provider.api:
    resource: '@ApplicationProjectSecurityUserBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.project.content:
    resource: '@ApplicationProjectContentBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.project.media:
    resource: '@ApplicationProjectMediaBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.project.setting:
    resource: '@ApplicationProjectSettingBundle/Resources/config/routes/routes.yaml'
    prefix: /

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

#api_login_check:
#    path: /api/login_check

app.swagger_ui:
    path: /api
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app.swagger:
    path: /api.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger }

###############################################################################
# Schema Bundles Routes
###############################################################################

application.internit.empresabundle:
    resource: '@ApplicationInternitEmpresaBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.enderecobundle:
    resource: '@ApplicationInternitEnderecoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.clientebundle:
    resource: '@ApplicationInternitClienteBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.setoratuacaobundle:
    resource: '@ApplicationInternitSetorAtuacaoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.solucaobundle:
    resource: '@ApplicationInternitSolucaoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.projetobundle:
    resource: '@ApplicationInternitProjetoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.departamentobundle:
    resource: '@ApplicationInternitDepartamentoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.contatobundle:
    resource: '@ApplicationInternitContatoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.curriculobundle:
    resource: '@ApplicationInternitCurriculoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.cargobundle:
    resource: '@ApplicationInternitCargoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.objetivobundle:
    resource: '@ApplicationInternitObjetivoBundle/Resources/config/routes/routes.yaml'
    prefix: /

application.internit.sitesdesenvolvidosbundle:
    resource: '@ApplicationInternitSitesDesenvolvidosBundle/Resources/config/routes/routes.yaml'
    prefix: /

