# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'pt_BR'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # overload kernel exception
    #    App\Application\Project\ContentBundle\EventListener\ExceptionListener:
    #        tags:
    #            - { name: kernel.event_listener, event: kernel.exception }

    #    App\Application\Project\SecurityProviderApiBundle\EventListener\ExceptionListener:
    #        tags:
    #            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    #
    #


    # ####################################################################################
    # injeções de dependências

    #    app.menu_listener:
    #        class: App\Application\Project\ContentBundle\EventListener\MenuBuilderListener
    #        tags:
    #            - { name: kernel.event_listener, event: sonata.admin.event.configure.menu.sidebar, method: addMenuItems }
    #        arguments:


    #    admin.custom:
    #        class: App\Admin\CustomAdmin
    #        tags:
    #            - { name: sonata.admin, model_class: App\Entity\Custom, manager_type: orm, label: Category, security_handler: App\Application\Project\AdminBundle\Security\Handler }


    # ####################################################################################
    # serviços padrões da estrutura do projeto

    # Content Bundle
    project.content.content:
        class: App\Application\Project\ContentBundle\Admin\ContentAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\ContentBundle\Entity\Content,
                controller: App\Application\Project\ContentBundle\Controller\ContentAdminController,
                show_in_dashboard: false,
                on_top: false,
                group: "Content",
                label: Content,
                icon: 'fa fa-solid fa-passport',
            }
            #- { name: sonata.admin, manager_type: orm, group: "Content", label: User, on_top: false, icon: 'fa fa-solid fa-user',, show_in_dashboard: false }

    project.content.setting:
        class: App\Application\Project\SettingBundle\Admin\SmtpEmailAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SettingBundle\Entity\SmtpEmail,
                controller: App\Application\Project\SettingBundle\Controller\SmtpEmailAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Configurações",
                label: SMTP,
                icon: 'fas fa-cogs',
            }
            #- { name: sonata.admin, manager_type: orm, group: "Content", label: User, on_top: false, icon: 'fa fa-solid fa-user',, show_in_dashboard: false }






    # ####################################################################################
    # Provedor de usuário ADMIN

    project.security.provider.admin.user:
        class: App\Application\Project\SecurityAdminBundle\Admin\UserAdminAdmin
        calls:
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityAdminBundle\Entity\UserAdmin,
                controller: App\Application\Project\SecurityAdminBundle\Controller\UserAdminAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Admin",
                label: Administradores,
                icon: 'fa fa-solid fa-shield-alt',
            }

    project.security.provider.admin.group:
        class: App\Application\Project\SecurityAdminBundle\Admin\GroupAdminAdmin
        calls:
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityAdminBundle\Entity\GroupAdmin,
                controller: App\Application\Project\SecurityAdminBundle\Controller\GroupAdminAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Admin",
                label: Grupos,
                icon: 'fa fa-solid fa-shield-alt',
            }

    # ####################################################################################
    # Provedor de usuário API

    project.security.provider.api.user:
        class: App\Application\Project\SecurityUserBundle\Admin\UserAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityUserBundle\Entity\User,
                controller: App\Application\Project\SecurityUserBundle\Controller\UserAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Usuários",
                label: Usuários,
                icon: 'fa fa-solid fa-users',
            }

    project.security.provider.api.group:
        class: App\Application\Project\SecurityUserBundle\Admin\GroupAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Project\SecurityUserBundle\Entity\Group,
                controller: App\Application\Project\SecurityUserBundle\Controller\GroupAdminController,
                show_in_dashboard: true,
                on_top: false,
                group: "Acesso Usuários",
                label: Grupos,
                icon: 'fa fa-solid fa-users',
            }

    # ####################################################################################
    # por favor, note que as últimas definições sao da estrutura padrão do projeto
    # adicione mais definições de serviço quando for necessária abaixo


    # Services Schemas Bundle
    # ####################################################################################
    internit.empresabundle.empresa:
        class: App\Application\Internit\EmpresaBundle\Admin\EmpresaAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\EmpresaBundle\Entity\Empresa,
                controller: App\Application\Internit\EmpresaBundle\Controller\EmpresaAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Empresa",
                label: Empresa,
                icon: 'fa fa-solid fa-book',
            }

    internit.enderecobundle.endereco:
        class: App\Application\Internit\EnderecoBundle\Admin\EnderecoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\EnderecoBundle\Entity\Endereco,
                controller: App\Application\Internit\EnderecoBundle\Controller\EnderecoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Endereco",
                label: Endereco,
                icon: 'fa fa-solid fa-book',
            }

    internit.clientebundle.cliente:
        class: App\Application\Internit\ClienteBundle\Admin\ClienteAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\ClienteBundle\Entity\Cliente,
                controller: App\Application\Internit\ClienteBundle\Controller\ClienteAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Cliente",
                label: Cliente,
                icon: 'fa fa-solid fa-book',
            }

    internit.setoratuacaobundle.setoratuacao:
        class: App\Application\Internit\SetorAtuacaoBundle\Admin\SetorAtuacaoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\SetorAtuacaoBundle\Entity\SetorAtuacao,
                controller: App\Application\Internit\SetorAtuacaoBundle\Controller\SetorAtuacaoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "SetorAtuacao",
                label: SetorAtuacao,
                icon: 'fa fa-solid fa-book',
            }

    internit.solucaobundle.solucao:
        class: App\Application\Internit\SolucaoBundle\Admin\SolucaoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\SolucaoBundle\Entity\Solucao,
                controller: App\Application\Internit\SolucaoBundle\Controller\SolucaoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Solucao",
                label: Solucao,
                icon: 'fa fa-solid fa-book',
            }

    internit.projetobundle.projeto:
        class: App\Application\Internit\ProjetoBundle\Admin\ProjetoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\ProjetoBundle\Entity\Projeto,
                controller: App\Application\Internit\ProjetoBundle\Controller\ProjetoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Projeto",
                label: Projeto,
                icon: 'fa fa-solid fa-book',
            }

    internit.departamentobundle.departamento:
        class: App\Application\Internit\DepartamentoBundle\Admin\DepartamentoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\DepartamentoBundle\Entity\Departamento,
                controller: App\Application\Internit\DepartamentoBundle\Controller\DepartamentoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Departamento",
                label: Departamento,
                icon: 'fa fa-solid fa-book',
            }

    internit.contatobundle.contato:
        class: App\Application\Internit\ContatoBundle\Admin\ContatoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\ContatoBundle\Entity\Contato,
                controller: App\Application\Internit\ContatoBundle\Controller\ContatoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Contato",
                label: Contato,
                icon: 'fa fa-solid fa-book',
            }

    internit.curriculobundle.curriculo:
        class: App\Application\Internit\CurriculoBundle\Admin\CurriculoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\CurriculoBundle\Entity\Curriculo,
                controller: App\Application\Internit\CurriculoBundle\Controller\CurriculoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Curriculo",
                label: Curriculo,
                icon: 'fa fa-solid fa-book',
            }

    internit.cargobundle.cargo:
        class: App\Application\Internit\CargoBundle\Admin\CargoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\CargoBundle\Entity\Cargo,
                controller: App\Application\Internit\CargoBundle\Controller\CargoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Cargo",
                label: Cargo,
                icon: 'fa fa-solid fa-book',
            }

    internit.objetivobundle.objetivo:
        class: App\Application\Internit\ObjetivoBundle\Admin\ObjetivoAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\ObjetivoBundle\Entity\Objetivo,
                controller: App\Application\Internit\ObjetivoBundle\Controller\ObjetivoAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "Objetivo",
                label: Objetivo,
                icon: 'fa fa-solid fa-book',
            }

    internit.sitesdesenvolvidosbundle.sitesdesenvolvidos:
        class: App\Application\Internit\SitesDesenvolvidosBundle\Admin\SitesDesenvolvidosAdmin
        tags:
            - {
                name: sonata.admin,
                manager_type: orm,
                model_class: App\Application\Internit\SitesDesenvolvidosBundle\Entity\SitesDesenvolvidos,
                controller: App\Application\Internit\SitesDesenvolvidosBundle\Controller\SitesDesenvolvidosAdminController,
                show_in_dashboard: true,
                on_top: true,
                group: "SitesDesenvolvidos",
                label: SitesDesenvolvidos,
                icon: 'fa fa-solid fa-book',
            }

